# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AnLuu Profile
email: lta.anluu@gmail.com
description: An Luu's Blog ^^
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

links:
  facebook: https://www.facebook.com/lta.anluu
  twitter: https://twitter.com/anluu471
  linkedin: https://www.linkedin.com/in/luuthienan/
  github: https://github.com/luuthienan

skills_devicons:
  - devicon-ruby-plain-wordmark
  - devicon-rails-plain-wordmark
  - devicon-html5-plain-wordmark
  - devicon-css3-plain-wordmark
  - devicon-sass-original
  - devicon-javascript-plain
  - devicon-bootstrap-plain-wordmark
  - devicon-jquery-plain-wordmark
  - devicon-ubuntu-plain-wordmark
  - devicon-git-plain-wordmark
  - devicon-heroku-original-wordmark
  - devicon-mysql-plain-wordmark
  - devicon-postgresql-plain-wordmark

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

experiences:
  - name: QUOINE
    position: Backend Developer
    start_time: 05/2018
    end_time: Present
    projects:
      - name: QUOINEX, QRYPTOS Backend
        url: https://quoinex.com
        description: QUOINEX and QRYPTOS is crypto exchange platforms that allows users to buy bitcoin and other major digital currencies. QUOINEX supports multiple fiat currencies and several of the world's largest crypto coins and tokens. QRYPTOS is only support crypto coins
        team_size: 10
        responsibility: Maintaining, discussing with teammates to get clear requirements. Develop feature ICO support for QRYPTOS
        technology: Ruby on Rails, PostgreSQL, Redis, Heroku

  - name: Golden Owl Consulting
    position: Intern - Fresher
    start_time: 06/2016
    end_time: 01/2018
    projects:
      - name: Nexlec
        url: https://nexlec.com
        description: Nexlec is a global online market place for Professionals to easily search for career education courses. The training courses include Lectures, Seminars, Practicals, Conferences, and Online Courses
        team_size: 3
        responsibility: Discussing with customer and teammates to get clear all requirements. Develop new features
        technology: Ruby on Rails, HTML5, Stripe API, AWS, Heroku, PostgreSQL
      - name: Narratrs
        url: https://play.google.com/store/apps/details?id=com.oneninesocial.narratrs&hl=en
        description: A mobile app which create content on Facebook and Instagram for brands that pay you for your content today.
        team_size: 4
        responsibility: Maintaining, discussing with api team to clear requirements. Develop new UI
        technology: Javascript, Ionic v1, Cordova
